#!/bin/bash
args=("$@")
BRANCH=${args[0]}

for i in $(ls -d */);
  do
    FOLDER=${i%%/}
    echo "Checking out ${BRANCH} for ${FOLDER}";
    cd $FOLDER;
    git checkout ${BRANCH};
    cd ./../
  done